export interface Hotel {
  name: string;
  address: string;
}

export interface HotelNeighborhood {
  label: string;
  hotels: Hotel[];
}

export const HOTELS_BY_NEIGHBORHOOD: HotelNeighborhood[] = [
  {
    label: 'San Telmo',
    hotels: [
      { name: 'América del Sur Hostel', address: 'Chacabuco 718' },
      { name: 'Bohemia Buenos Aires Hotel', address: 'Perú 845' },
      { name: 'Cassa Lepage Art Hotel', address: 'Bolivar 365' },
      { name: 'Granados Hostel', address: 'Chile 374' },
      { name: 'Hotel Anselmo Buenos Aires – Curio Collection by Hilton', address: 'Anselmo Aieta 1069' },
      { name: 'Lemon Suites Apartments', address: 'Chacabuco 1072' },
      { name: 'Lina Tango Gest House', address: 'Estados Unidos 780' },
      { name: 'Los Robles', address: 'Estados Unidos 827' },
      { name: 'Los Tres Reyes', address: 'Brasil 423' },
      { name: 'Lugar Gay Buenos Aires', address: 'Defensa 1120' },
      { name: 'Madero Urbano Studios – ADL', address: 'Azopardo 770' },
      { name: 'Patios de San Telmo', address: 'Chacabuco 752' },
      { name: 'Piedras Suites', address: 'Piedras 906' },
      { name: 'Portal del Sur', address: 'Av. Hipólito Irigoyen' },
      { name: 'Posta de Piedras', address: 'Piedras 906' },
      { name: 'Puerto Limón', address: 'Chacabuco 1080' },
      { name: 'Republica San Telmo', address: 'Chacabuco 1163' },
      { name: 'Ribera Sur', address: 'Av. Paseo Colón 1145' },
      { name: 'San Telmo Flats', address: 'Piedras 990' },
      { name: 'Sant Telmo Suites Studio', address: 'Cochabamba 760' },
      { name: 'Sudamerika Hostel & Suites', address: 'Yrigoyen Hipólito 951' },
      { name: 'Telmho Hotel', address: 'Defensa 1086' },
      { name: 'Tiana', address: 'Humberto 1º 629' },
      { name: 'Washington', address: 'Garay Juan De Av. 340' },
    ],
  },
  {
    label: 'Puerto Madero',
    hotels: [
      { name: 'Alvear Icon', address: 'Aimé Painé 1130' },
      { name: 'Bayside Forum', address: 'Av. Juana Manso 153' },
      { name: 'City Madero', address: 'Olga Cossettini 1540' },
      { name: 'Faena Hotel Buenos Aires', address: 'Martha Salotti 445' },
      { name: 'Hilton', address: 'Macacha Güemes 351' },
      { name: 'Holiday Inn Express Puerto Madero', address: 'Leandro N. Alem Av. 770' },
      { name: 'Lumiere', address: 'Olga Cossettini 1540' },
      { name: 'Madero Buenos Aires', address: 'Rosario Vera Peñaloza 360' },
      { name: 'Residencia Faena', address: 'Martha Salotti 445' },
      { name: 'SLS Puerto Madero', address: 'Rosario Vera Peñaloza 400' },
    ],
  },
  {
    label: 'Palermo',
    hotels: [
      { name: '1828 Smart Hotel', address: 'Fray Justo Santa María de Oro 1828' },
      { name: 'Alpino', address: 'Cabello 3318' },
      { name: 'Aries', address: 'Gascón 1147' },
      { name: 'Art Factory Palermo', address: 'Costa Rica 4353' },
      { name: 'Art Factory Soho', address: 'Charcas 4500' },
      { name: 'AWWA Suites & Spa', address: 'Lafinur 3370' },
      { name: 'Be Hollywood', address: 'Humboldt 1716' },
      { name: 'Be Jardin Escondido by Coppola', address: 'Gorriti 4746' },
      { name: 'Bys Palermo', address: 'Acuña de Figueroa 1263' },
      { name: 'Bulnes Eco Suites', address: 'Bulnes 1905' },
      { name: 'Casasur Palermo Hotel', address: 'Costa Rica 6032' },
      { name: 'Costa Rica', address: 'Costa Rica 4137' },
      { name: 'Duque Hotel Boutique', address: 'Guatemala 4364' },
      { name: 'Feel Apartments', address: 'Fray Justo Santa María de Oro 2047' },
      { name: 'Fierro Hotel Boutique', address: 'Soler 5862' },
      { name: 'Home Buenos Aires', address: 'Honduras 5860' },
      { name: 'Hotel Pampa Plaza', address: 'La Pampa 777' },
      { name: 'Ian Hotel', address: 'Cnel. Niceto Vega 5832' },
      { name: 'Ilum Experience Home', address: 'El Salvador 5726' },
      { name: 'Infinito Hotel Eco Design', address: 'Arenales 3689' },
      { name: "Key's Hotel", address: 'Zapata 315' },
      { name: 'Koten Hotel Palermo Soho', address: 'Guemes 4651' },
      { name: "L'Hotel Palermo", address: 'Thames 1562' },
      { name: 'Legado Mitico', address: 'Gurruchaga 1848' },
      { name: 'Let Sun Hotel Boutique', address: 'Fitz Roy 1527' },
      { name: 'Magnolia Hotel', address: 'Alvarez Julián 1746' },
      { name: 'Malevo Muraña Hostel', address: 'Russel 5050' },
      { name: 'Magistral', address: 'Borges Jorge Luis 1937' },
      { name: 'Miño', address: 'Gallo 1258' },
      { name: 'Mine Hotel Boutique', address: 'Gorriti 4770' },
      { name: 'Miravida Soho', address: 'Darragueyra 2050' },
      { name: 'Omega', address: 'Paraguay 2991' },
      { name: 'OWN Grand Palermo Soho', address: 'Gurruchaga 2121' },
      { name: 'Palo Santo Hotel', address: 'Bonpland 2275' },
      { name: 'Palermo Hotel', address: 'Godoy Cruz 2725' },
      { name: 'Palermo Suites Buenos Aires Apartments', address: 'Fray Justo Santa María de Oro 2529' },
      { name: 'Paname', address: 'Godoy Cruz 2774' },
      { name: 'Play Hostel Arcos', address: 'Charcas 4752' },
      { name: 'Play Hostel Soho', address: 'Guatemala 4636' },
      { name: 'Rendez Vous Hotel', address: 'Bonpland 1484' },
      { name: 'The Glu Hotel', address: 'Godoy Cruz 1733' },
      { name: 'Torre Cristoforo Colombo Suites', address: 'Fray Justo Santa María de Oro 2747' },
      { name: 'Vitrum Hotel', address: 'Gorriti 5641' },
    ],
  },
  {
    label: 'Retiro',
    hotels: [
      { name: '8 de Octubre', address: 'Paraguay 1420' },
      { name: 'Algodón Mansión', address: 'Montevideo 1647' },
      { name: 'Alvear Art', address: 'Suipacha 1036' },
      { name: 'Argenta Tower', address: 'Juncal 868' },
      { name: 'Bisonte Libertad', address: 'Libertad 902' },
      { name: 'Bisonte Palace Hotel', address: 'Alvear Marcelo T. De 902' },
      { name: 'Carles Hotel', address: 'Juncal 798' },
      { name: 'Carlton Solans', address: 'Libertad 1180' },
      { name: 'Casa Calma', address: 'Suipacha 1015' },
      { name: 'Charcas Apart', address: 'Marcelo Torcuato de Alvear 776' },
      { name: 'Circulo Militar', address: 'Av. Santa Fé 750' },
      { name: 'Cls Rentals', address: 'Suipacha 1235' },
      { name: 'Dazzler Tower Maipu', address: 'Maipú 856' },
      { name: 'Dazzler Tower San Martín', address: 'San Martín 920' },
      { name: 'Deco Collection', address: 'Suipacha 1359' },
      { name: 'Del Pilar AP', address: 'Juncal 1230' },
      { name: 'Diplomat', address: 'San Martín 918' },
      { name: 'Dolmen Hotel', address: 'Suipacha 1079' },
      { name: 'Dora', address: 'Maipú 963' },
      { name: 'Efe Cowork Hotel', address: 'Paraguay 474' },
      { name: 'El Conquistador', address: 'Suipacha 948' },
      { name: 'El Misti Hotel', address: 'Paraguay 372' },
      { name: 'Embajador', address: 'Pellegrini Carlos 1185' },
      { name: 'Emperador Buenos Aires', address: 'Av. Del Libertador 420' },
      { name: 'Feirs Park', address: 'Esmeralda 1366' },
      { name: 'Four Seasons', address: 'Posadas 1086' },
      { name: 'Gran Hotel Dora', address: 'Maipu 963' },
      { name: 'HI Recoleta', address: 'Libertad 1216' },
      { name: 'Hj Plaza Florida', address: 'Florida 944' },
      { name: 'Hotel Buenos Aires', address: 'Suipacha 854' },
      { name: 'Hotel Central Cordoba', address: 'San Martín 1021' },
      { name: 'Howard Johnson Plaza Florida Street', address: 'Florida 944' },
      { name: 'Impala', address: 'Libertad 1215' },
      { name: 'Ker Recoleta', address: 'Marcelo Torcuato de Alvear 1368' },
      { name: 'Le B Club Boutique', address: 'Talcahuano 1253' },
      { name: 'Le Petit Rental Suites', address: 'Esmeralda 933' },
      { name: 'Leonardo Da Vinci Suites', address: 'Libertad 1224' },
      { name: 'Loi Suites Esmeralda', address: 'Marcelo Torcuato de Alvear 842' },
      { name: 'Melia Buenos Aires', address: 'Reconquista 945' },
      { name: 'NH Crillon', address: 'Av. Sta. Fe 796' },
      { name: 'NH Florida', address: 'San Martín 839' },
      { name: 'NH Lancaster', address: 'Av. Córdoba 405' },
      { name: 'Obelisco Studio', address: 'Av. Córdoba 875' },
      { name: 'Palacio Paz Hotel', address: 'Av. Sta. Fe 760' },
      { name: 'Park Royal', address: 'Suipacha 1092' },
      { name: 'Park Tower Hotel', address: 'Av. Leandro N. Alem 1193' },
      { name: 'Pestana', address: 'Carlos Pellegrini 877' },
      { name: 'Presidente', address: 'Cerrito 850' },
      { name: 'Principado', address: 'Paraguay 481' },
      { name: 'Quartier Basavilbaso', address: 'Basavilbaso 1350' },
      { name: 'Ramada By Wyndham', address: 'Paraguay 857' },
      { name: 'Recoleta Small', address: 'Talcahuano 1253' },
      { name: 'Regente Palace', address: 'Suipacha 964' },
      { name: 'San Roman', address: 'Talcahuano 1131' },
      { name: 'Serena', address: 'Libertad 1617' },
      { name: 'Sheltown', address: 'Marcelo Torcuato de Alvear 742' },
      { name: 'Sofitel Recoleta', address: 'Posadas 1232' },
      { name: 'Solans Carlton', address: 'Libertad 1180' },
      { name: 'Suipacha 1373', address: 'Suipacha 1373' },
      { name: 'Suma Recoleta', address: 'Parera 183' },
      { name: 'The Recoleta Hostel', address: 'Libertad 1216' },
      { name: 'Top Rentals Downtown', address: 'Esmeralda 920' },
      { name: 'Tres Sargentos', address: 'Tres Sargentos 345' },
      { name: 'UP Retiro', address: 'Marcelo Torcuato de Alvear 444' },
      { name: 'Victory', address: 'Maipú 880' },
      { name: 'Waldorf', address: 'Paraguay 450' },
    ],
  },
  {
    label: 'Recoleta',
    hotels: [
      { name: 'A Hotel', address: 'Larrea 1259' },
      { name: 'Administración Callao', address: 'Av. Callao 1178' },
      { name: 'Alta Piazza', address: 'Jose León Pagano 2634' },
      { name: 'Alvear Palace', address: 'Av. Alvear 1891' },
      { name: 'Anchorena Apara Hotel', address: 'Dr. Tomás Manuel de Anchorena 1121' },
      { name: 'Ancon Hotel', address: 'Marcelo Torcuato de Alvear 2223' },
      { name: 'Aq Tailored Suites', address: 'Montevideo 937' },
      { name: 'Arc Arenales', address: 'Arenales 2644' },
      { name: 'Arc Recoleta Boutique', address: 'Rodriguez Peña 2155' },
      { name: 'Arenales Hotel', address: 'Arenales 2984' },
      { name: 'Arenales Suites', address: 'Arenales 2850' },
      { name: 'Art Galery – A Hotel', address: 'Azcuénaga 1268' },
      { name: 'Art Suites', address: 'Azcuénaga 1465' },
      { name: 'Art Suites and Gallery', address: 'Peña 2268' },
      { name: 'Ayacucho Palace', address: 'Ayacucho 1408' },
      { name: 'Ayres de Recoleta', address: 'Pres. José Evaristo Uriburu 1756' },
      { name: 'Ayres de Recoleta Plaza', address: 'Guido 1980' },
      { name: 'Bauen Apart', address: 'Av. Córdoba 1827' },
      { name: 'Bel Air Bs As Hotel', address: 'Arenales s/n' },
      { name: 'Blank Hotel Recoleta', address: 'Peña 2049' },
      { name: 'Buenos Aires Design Ce', address: 'Marcelo Torcuato de Alvear 1695' },
      { name: 'Callao Suites Apart Hotel Recoleta', address: 'Callao Av. 1062' },
      { name: 'Casa Bevant', address: 'Vicente López 1827' },
      { name: 'Casa Franca Recoleta Hostel', address: 'José Andrés Pacheco de Melo 1854' },
      { name: 'Casa Sur Recoleta', address: 'Av. Callao 1823' },
      { name: 'Ch Recoleta Suites', address: 'Junín 1743' },
      { name: 'Concorde Callao', address: 'Av. Callao 1234' },
      { name: 'Cordoba Suites', address: 'Av. Córdoba 1827' },
      { name: 'Cyan Americas Towers', address: 'Libertad 1070' },
      { name: 'Cyan Recoleta', address: 'Junín 1743' },
      { name: 'Dazzler Tower Recoleta', address: 'Av. Gral. Las Heras 2161' },
      { name: 'Epico', address: 'Laprida 1902' },
      { name: 'Etoile', address: 'Pres. Roberto M. Ortiz 1835' },
      { name: 'Guido Palace', address: 'Guido 1780' },
      { name: 'Hj Boutique Recoleta', address: 'Peña 2049' },
      { name: 'Hotel Club Frances', address: 'Rodríguez Peña 1832' },
      { name: 'Hotel Del Prado', address: 'Paraguay 2385' },
      { name: 'Hotel Fuerza Aérea', address: 'Paraguay 2652' },
      { name: 'HUB Porteño', address: 'Rodríguez Peña 1967' },
      { name: 'Intersur Recoleta', address: 'Av. Callao 1764' },
      { name: 'IQ Callao', address: 'José Andrés Pacheco de Melo 1857' },
      { name: 'IQ Recoleta Plaza', address: 'Montevideo 1250' },
      { name: 'Juncal Palace', address: 'Juncal 2282' },
      { name: 'Le Batiment Recoleta', address: 'Paraguay 2862' },
      { name: 'Le Cinque Lusso', address: 'Av. Pueyrredón 1940' },
      { name: 'Loi Suites Arenales', address: 'Vicente López 1955' },
      { name: 'Loi Suites Recoleta', address: 'Vicente López 1955' },
      { name: 'Los Dominguez Apartamentos', address: 'Av. Callao 1178' },
      { name: 'Luco Hotel', address: 'Av. Córdoba 2409' },
      { name: 'Marseilles De Anges', address: 'Arenales 1392' },
      { name: 'Mayla', address: 'Rodríguez Peña 2076' },
      { name: 'Melia Recoleta', address: 'Posadas 1557' },
      { name: 'Mio Buenos Aires', address: 'Av. Pres. Manuel Quintana 465' },
      { name: 'Optimus', address: 'Marcelo Torcuato de Alvear 2320' },
      { name: 'Palacio Duhau – Park Hyatt', address: 'Av. Alvear 1661' },
      { name: 'Palladino Hotel Buenos Aires', address: 'Av. Callao 924' },
      { name: 'Patios de Recoleta', address: 'José Andrés Pacheco de Melo 2019' },
      { name: 'Petit Recoleta Hostel', address: 'Pres. José Evaristo Uriburu 1183' },
      { name: 'Petit Recoleta Suites', address: 'Marcelo Torcuato de Alvear 1893' },
      { name: 'Picaluga Apart Hotel', address: 'Marcelo Torcuato de Alvear 1563' },
      { name: 'Poetry Building Recoleta', address: 'Junín 1280' },
      { name: 'Prince', address: 'Arenales 1627' },
      { name: 'Principe', address: 'Laprida 1454' },
      { name: 'Recoleta Park By Bens', address: 'Libertad 1283' },
      { name: 'Recoleta Flats', address: 'Montevideo 1250' },
      { name: 'Recoleta Grand Hotel', address: 'Av. Gral. Las Heras 1745' },
      { name: 'Recoleta Guest House', address: 'Ayacucho 922' },
      { name: 'Reina Madre', address: 'Dr. Tomás Manuel de Anchorena 1118' },
      { name: 'Residencia Recoleta', address: 'Arenales 2131' },
      { name: 'San Diego Recoleta Apartments', address: 'Rodríguez Peña 1158' },
      { name: 'Sheraton Buenos Aires', address: 'Esmeralda 1366' },
      { name: 'Sileo', address: 'Azcuénaga 1968' },
      { name: 'Studio Pueyrredon', address: 'Av. Pueyrredón 1770' },
      { name: 'Sudamerika Hostel Recoleta', address: 'Arenales 2644' },
      { name: 'TPYN Recoleta', address: 'Rodríguez Peña 1061' },
      { name: 'Trianon', address: 'Av. Callao 1869' },
      { name: 'Ulises Recoleta Suites', address: 'Ayacucho 2016' },
      { name: 'UP Recoleta Hotel', address: 'José León Pagano 2684' },
      { name: 'Urban Suites Recoleta', address: 'Junín 1727' },
      { name: 'Wilton', address: 'Av. Callao 1162/64' },
    ],
  },
  {
    label: 'Centro',
    hotels: [
      { name: '474 Buenos Aires Hotel', address: 'San Martín 474' },
      { name: '725 Continental Hotel', address: 'Diagonal Norte Av. 725' },
      { name: '818 Suites', address: 'Av. Corrientes 820' },
      { name: 'A & E Buenos Aires', address: 'Tucumán 425' },
      { name: 'Abasto Plaza', address: 'Corrientes 3190' },
      { name: 'Alcazar', address: 'Av. de Mayo 935' },
      { name: 'Alma de Buenos Aires', address: 'Suipacha 536' },
      { name: 'Alma del Plata', address: 'Santiago del Estero 727' },
      { name: 'Amerian', address: 'Reconquista 699' },
      { name: 'Americano Hotel', address: 'Rodriguez Peña 265' },
      { name: 'Apart Lima', address: 'Lima 265' },
      { name: 'Apart Monserrat', address: 'Av. Hipólito Yrigoyen 1310' },
      { name: 'Apassionata Tango', address: 'Pasco 272' },
      { name: 'Arc Callao Studio y Suites', address: 'Viamonte 1815' },
      { name: 'Argentina Tango Hotel', address: 'Suipacha 545' },
      { name: 'Art Factory Hostel', address: 'Piedras 545' },
      { name: 'Astoria', address: 'Av. de Mayo 916' },
      { name: 'Atlas Towers', address: 'Av. Corrientes 1178' },
      { name: 'Ayres Porteños Tango', address: 'Chacabuco 615' },
      { name: 'Bagu Buenos Aires', address: 'Tte. Gral. Juan Domingo Perón 838' },
      { name: 'Bahia Hotel', address: 'Av. Corrientes 1212' },
      { name: 'Bauen', address: 'Av. Callao 360' },
      { name: 'Big Adventure Hostel', address: 'Hipólito Yrigoyen 1156' },
      { name: 'Bristol Hotel', address: 'Cerrito 286' },
      { name: 'Broadway Hotel & Suites', address: 'Corrientes Av. 1173' },
      { name: 'Carsson', address: 'Viamonte 650' },
      { name: 'Centuria Hotel', address: 'Suipacha 30' },
      { name: 'Chile', address: 'Av. de Mayo 1297' },
      { name: 'Claridge Hotel', address: 'Tucuman 535' },
      { name: 'Columbia Palace', address: 'Av. Corriente 1543' },
      { name: 'Comfort Buenos Aires', address: 'Paraná 704' },
      { name: 'Concorde', address: '25 de Mayo 630' },
      { name: 'Crisol Suites Catalinas', address: 'Tucumán 313' },
      { name: 'Da Vinci Hotel', address: 'Tucuman 857' },
      { name: 'De las Luces', address: 'Adolfo Alsina 525' },
      { name: 'Design Suites', address: 'Tacuarí 243' },
      { name: 'Duomi Plaza Hotel', address: 'Bartolomé Mitre 1480' },
      { name: 'El Cabildo', address: 'Lavalle 748' },
      { name: 'Esmeralda Palace', address: 'Esmeralda 527' },
      { name: 'Esplendor Buenos Aires', address: 'San Martín 780' },
      { name: 'Esplendor By Wyndham Bs As Tango', address: 'Av. Rivadavia 947' },
      { name: 'Estoril', address: 'Av. de Mayo 1385' },
      { name: 'Eurobuilding Hotel', address: 'Lima 187' },
      { name: 'Europlaza Hotel & Suites', address: 'Montevideo 327' },
      { name: 'Exe Colon', address: 'Carlos Pellegrini 507' },
      { name: 'Facon Grande', address: 'Reconquista 645' },
      { name: 'Franca City Hostel', address: 'Av. de Mayo 1410' },
      { name: 'Galerías Hotel', address: 'Tucumán 651' },
      { name: 'Globales Republica Hotel', address: 'Cerrito 370' },
      { name: 'Goya Hotel', address: 'Suipacha 748' },
      { name: 'Gran Hotel Ailen', address: 'Suipacha 18' },
      { name: 'Gran Hotel Argentino', address: 'Pellegrini Carlos 37' },
      { name: 'Gran Hotel Libertad', address: 'Libertad 249' },
      { name: 'Gran Via', address: 'Sarmiento 1450' },
      { name: 'Grand Boulevard', address: 'Bernardo de Irigoyen 432' },
      { name: 'Gran Brizo', address: 'Cerrito 180' },
      { name: 'Grand Hotel Faecys', address: 'Tucumán 570' },
      { name: 'Grand King', address: 'Lavalle 560' },
      { name: 'Holiday Inn Puerto Madero', address: 'Av. Leandro N. Alem 770' },
      { name: 'Hostel Club V&S', address: 'Viamonte 887' },
      { name: 'Hostel Suites Florida', address: 'Florida 328' },
      { name: 'Hostel Suites Obelisco', address: 'Av. Corrientes 830' },
      { name: 'Hotel Argentina', address: 'Suipacha 250' },
      { name: 'Hotel Avenida', address: 'Av. de Mayo 623' },
      { name: 'Hotel España', address: 'Tacuarí 80' },
      { name: 'Hotel Gran Sarmiento Buenos Aires', address: 'Sarmiento 1892' },
      { name: 'Hotel La Giralda', address: 'Tacuarí 17' },
      { name: 'Hotel Naciones', address: 'Av. Corrientes 1285' },
      { name: 'Hotel Porteño', address: 'Moreno 1150' },
      { name: 'HR Esmeralda Luxor', address: 'Esmeralda 675' },
      { name: 'HTL Urbano Buenos Aires', address: 'Tucumán 451' },
      { name: 'HUINID Obelisco Hotel', address: 'Sarmiento 1431' },
      { name: 'IBIS Buenos Aires Congreso', address: 'Av. Hipólito Yrigoyen 1592' },
      { name: 'IBIS Obelisco', address: 'Av. Corrientes 1344' },
      { name: 'IBIS Styles', address: 'Av. Corrientes 632' },
      { name: 'Icaro Suites', address: 'Montevideo 229' },
      { name: 'Imperial Park', address: 'Lima 101' },
      { name: 'Intercontinental', address: 'Moreno 809' },
      { name: 'Internacional', address: 'Bernardo de Irigoyen 552' },
      { name: 'Intersur Suites', address: 'Av. Corrientes 1984' },
      { name: 'Kenton Palace', address: 'Defensa 383' },
      { name: 'La Argentina', address: 'Avenida de Mayo 860' },
      { name: 'La Piedad Hotel', address: 'Bartolomé Mitre 1156' },
      { name: 'La Rocca Hostel', address: 'Av. Callao 341' },
      { name: 'Lafayette', address: 'Reconquista 546' },
      { name: 'Lennox', address: 'Talcahuano 52' },
      { name: 'Libertador Hotel', address: 'Av. Córdoba 690' },
      { name: 'Liberty (IBIS Styles Florida)', address: 'Av. Corrientes 632' },
      { name: 'Lisboa Palace Hotel', address: 'Bartolomé Mitre 1282' },
      { name: 'Los Patios de Monserrat', address: 'Piedras 83' },
      { name: 'Maison Ramon', address: 'Adolfo Alsina 1266' },
      { name: 'Marbella', address: 'Av. de Mayo 1261' },
      { name: 'Marriott', address: 'Carlos Pellegrini 551' },
      { name: 'Mayflowers Suites', address: 'Paraná 720' },
      { name: 'Merit San Telmo', address: 'Adolfo Alsina 801' },
      { name: 'Milan', address: 'Montevideo 335' },
      { name: 'Milhouse Hipo', address: 'Av. Hipólito Yrigoyen 959' },
      { name: 'Monarca', address: '25 de Mayo 724' },
      { name: 'Moreno', address: 'Moreno 820' },
      { name: 'Napoleon', address: 'Av. Rivadavia 1364' },
      { name: 'NH Buenos Aires 9 de Julio', address: 'Cerrito 154' },
      { name: 'NH Centro Histórico', address: 'Bolívar 120' },
      { name: 'NH City', address: 'Bolívar 160' },
      { name: 'NH Latino', address: 'Suipacha 309' },
      { name: 'Nogaro', address: 'Av. Presidente Julio A. Roca 562' },
      { name: 'Novel Hotel', address: 'Av. de Mayo 915' },
      { name: 'Novotel', address: 'Av. Corrientes 1334' },
      { name: 'Obelisco Hoteles', address: 'Suipacha 547' },
      { name: 'Own Madero', address: 'Azopardo 419' },
      { name: 'Palacio Raggio', address: 'Moreno 502' },
      { name: 'Park Silver Obelisco', address: 'Cerrito 330' },
      { name: 'Parlamento', address: 'Rodríguez Peña 61' },
      { name: 'Plaza Roma', address: 'Av. Leandro N. Alem s/n' },
      { name: 'Posada de la Luna', address: 'Perú 565' },
      { name: 'Regal Pacific', address: '25 de Mayo 764' },
      { name: 'Regis', address: 'Lavalle 813' },
      { name: 'Ritz Hotel', address: 'Av. de Mayo 1111' },
      { name: 'Rochester Classic', address: 'Esmeralda 556' },
      { name: 'Rochester Concept', address: 'Maipú 572' },
      { name: 'Roma', address: 'Av. de Mayo 1413' },
      { name: 'Salles', address: 'Cerrito 208' },
      { name: 'Savoy', address: 'Av. Callao 181' },
      { name: 'Sensazione Hotel', address: 'Cerrito 22' },
      { name: 'Splendid', address: 'Av. Rivadavia 950' },
      { name: 'St Nicholas', address: 'Bartolomé Mitre 1691' },
      { name: 'Suipacha Inn Hotel', address: 'Suipacha 515' },
      { name: 'Tanguero Hotel Boutique', address: 'Suipacha 780' },
      { name: 'Tribeca', address: 'Bartolomé Mitre 1265' },
      { name: 'Tritone', address: 'Maipú 657' },
      { name: 'Tucumán Palace', address: 'Tucumán 384' },
      { name: 'Two Buenos Aires', address: 'Moreno 785' },
      { name: 'Unique Executive Central', address: 'Av. Pres. Roque Sáenz Peña 1178' },
      { name: 'Unique Palacio San Telmo', address: 'Moreno 606' },
      { name: 'Uno Buenos Aires Suites', address: 'Av. Rivadavia 1944' },
      { name: 'UP America Plaza', address: 'Bartolomé Mitre 1744' },
      { name: 'UP Congreso', address: 'Montevideo 86' },
      { name: 'UP Viamonte', address: 'Viamonte 1373' },
      { name: 'Upoint Flats', address: 'Sarmiento 348' },
      { name: 'V Y S Hostel', address: 'Viamonte 887' },
      { name: 'Vedra', address: 'Av. de Mayo 1350' },
      { name: 'Viajero Hostel', address: 'Venezuela 649' },
      { name: 'Village Garden Apart Hotel', address: 'Suipacha 250' },
    ],
  },
];

export const ALL_HOTELS = HOTELS_BY_NEIGHBORHOOD.flatMap((n) =>
  n.hotels.map((h) => ({ ...h, neighborhood: n.label })),
);
